name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        # On ajoute le chemin explicite vers ton main.dart
        run: flutter build apk --release --target lib/main.dart
        
      - uses: actions/upload-artifact@v4
        with:
          name: ShieldCheck-Agent
          path: build/app/outputs/flutter-apk/app-release.apk
